name: "AutoRenraku"
description: "Automatic code review of Pharo Code using Reneraku Critiques"
author: badetitou
branding:
  color: orange
  icon: check-circle
inputs:
  pat:
    description: 'The Personal Access Token, or GitHub app token, to be used for publishing the comments'
    required: true
runs:
  using: composite
  steps:
    - id: files
      uses: masesgroup/retrieve-changed-files@v3
      continue-on-error: true
      with:
        format: "space-delimited"
    - run: echo "changed_files=${{ steps.files.outputs.added_modified }}" >> "$GITHUB_ENV"
      shell: bash
    - run: $SMALLTALK_CI_VM $SMALLTALK_CI_IMAGE st ${{ github.action_path }}/ci/autoReneraku.st
      shell: bash
      env:
        PAT: ${{ inputs.pat }}
        PULL_REQUEST_NUMBER: ${{ github.event.number }}
        COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
